###
GET http://localhost:9000/API/Contacts HTTP/1.1

###
POST http://localhost:9000/API/Contacts HTTP/1.1
Content-Type: application/json

{
    "Nombres": "Prueba unitaria",
    "Apellidos": "Create",
    "CorreoElectronico": "Create@gmail.com",
    "Edad": 50,
    "Celular": "4272829",
    "Ciudad": "Cali",
    "Direccion": "Create office"
}

###
PUT http://localhost:9000/API/Contacts/13 HTTP/1.1
Content-Type: application/json

{
    "Nombres": "Prueba unitaria Put",
    "Apellidos": "Update",
    "CorreoElectronico": "Update@gmail.com",
    "Edad": 25,
    "Celular": "4272829",
    "Ciudad": "Cali",
    "Direccion": "Update office"
}

###
DELETE http://localhost:9000/API/Contacts/13 HTTP/1.1


